apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: skillpulse-ns
  labels:
    app: backend-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-label
  template:
    metadata:
      labels:
        app: backend-label
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command: ["/bin/sh", "-c", "until nc -z mysql-svc 3306; do sleep 2; done"]
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"


      containers:
      - name: backend
        image: sach990p/skillpulse-backend:7493938
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: skillpulse-config
          - secretRef:
              name: skillpulse-secret

        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3