apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: skillpulse-ns
  labels:
    app: frontend-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-label
  template:
    metadata:
      labels:
        app: frontend-label
    spec:
      containers:
      - name: frontend
        image: sach990p/skillpulse-frontend:eac381c
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
             name: skillpulse-config
          - secretRef:
             name: skillpulse-secret