apiVersion: v1
kind: Secret
metadata:
  name: skillpulse-secret
  namespace: skillpulse-ns

type: Opaque

data:
  MYSQL_PASSWORD: c2tpbGxwdWxzZTEyMw==
  DB_PASSWORD: c2tpbGxwdWxzZTEyMw==
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkMTIz
