apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: skillpulse-ns
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command: ["/bin/sh", "-c", "until nc -z mysql-svc 3306; do sleep 2; done"]
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"

      containers:
      - name: skillpulse-backend
        image: sach990p/backend:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

        envFrom:
          - configMapRef:
              name: skillpulse-cm
          - secretRef:
              name: skillpulse-secrets

        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"


        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3

