apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: skillpulse-ns
  labels:
    app: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: mysql
          containerPort: 3306
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: skillpulse-cm
                key: MYSQL_USER

          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: skillpulse-cm
                key: MYSQL_DATABASE



          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: skillpulse-secrets
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: skillpulse-secrets
                key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"


        readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 15
            periodSeconds: 10
        livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5


        volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init
          configMap:
            name: mysql-init