kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: skillpulse-ns
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual

  hostPath:
    path: /mnt/data/mysql