apiVersion: v1
kind: Secret
metadata:
  name: skillpulse-secrets
  namespace: skillpulse-ns
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkMTIz
  DB_PASSWORD: c2tpbGxwdWxzZTEyMw==
  MYSQL_PASSWORD: c2tpbGxwdWxzZTEyMw==