name: GitOps CI - Build & Push to DockerHub

on:
  push:
    branches: [gitops]
    paths:
      - 'mysql/**'
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

permissions:
  contents: write

env:
  DOCKERHUB_REPO: sach990p/skillpulse-eks

jobs:
  build-and-push:
    name: Build, Test & Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # go-version: [ '1.19', '1.20', '1.21.x' ]
        include:
          - service: frontend
            dockerfile: ./frontend/Dockerfile
            context: ./frontend
            manifest: k8s/frontend.yml
            image_name: sach990p/skillpulse-frontend

          - service: backend
            dockerfile: ./backend/Dockerfile
            context: ./backend
            manifest: k8s/backend.yml
            image_name: sach990p/skillpulse-backend


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true 

    #   - name: Setup Go 1.21.x
    #     uses: actions/setup-go@v5
    #     with:
    #       # Semantic version range syntax or exact version of Go
    #       go-version: '1.21.x'
    #   - name: Install dependencies
    #     run: go get .
    #   - name: Test with Go
    #     run: go test -json > TestResults-${{ matrix.go-version }}.json
    #   - name: Upload Go test results
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: Go-results-${{ matrix.go-version }}
    #       path: TestResults-${{ matrix.go-version }}.json

      - name: Set image tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image_name }}:latest
            ${{ matrix.image_name }}:${{ steps.tag.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Kubernetes deployment manifest
        run: |
          sed -i "s|image: ${{ matrix.image_name }}:.*|image: ${{ matrix.image_name }}:${{ steps.tag.outputs.sha_short }}|" ${{ matrix.manifest }}


      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ matrix.manifest }}
          git diff --staged --quiet || git commit -m "ci: update ${{ matrix.service }} image to ${{ steps.tag.outputs.sha_short }} [skip ci]"
          git pull origin gitops --rebase
          git push origin gitops